Use process.cwd() instead of process.env.PWD
Windows Azure doesn't set process.env.PWD, but a simple string
concatenation using process.cwd() works just fine. I'm not using
path.join() here because on Windows systems the path seperator
character is backslash ("\") instead of slash ("/"):
http://en.wikipedia.org/wiki/Path_%28computing%29

Without this fix you'll see the following exception when running on
Windows Azure:

Tue Aug 27 2013 22:03:06 GMT+0000 (Coordinated Universal Time): Unaught
exception: TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.<anonymous>
(\\100.68.130.79\volume-24-default\2c3d84fd3e95e8aaaaec\9d446c52519340f4
9df1c437ee86f24c\site\wwwroot\node_modules\static-expiry\index.js:27:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function._load
(\\100.68.130.79\volume-24-default\2c3d84fd3e95e8aaaaec\9d446c52519340f4
9df1c437ee86f24c\site\wwwroot\node_modules\newrelic\lib\shimmer.js:151:3
8)
    at Module.require (module.js:364:17)

I worked around the issue by adding:
process.env.PWD = process.cwd();

before the require statement:
var expiry = require('static-expiry');